### PR TITLE
Create README_ES.md

### PR DESCRIPTION
**Pull request by LuigiBaute**
@elorzafe Any other suggestion? :+1:

### CODE REVIEW

**Comment by LuigiBaute** [comment]
@UnleashedMind @elorzafe Done! Check it out. :+1:

**Comment by elorzafe** [comment]
Cool! let me take a look. Thanks!

**Comment by LuigiBaute** [comment]
Hi! @elorzafe do you want to change anything else in the PR? Let me know! :+1:

**Review by mlabieniec — APPROVED** [review]
👍

**Pull request merged**
